### ISSUE TITLE
Export for OCR Problem

### ISSUE THREAD

**Issue by thk007** [Nuix/OCR-Candidates#1]
Hey Guys,

I'm noticing when I run the "Export for OCR" option I am getting an "undefined method 'mime_type' " error

I can't send through a screenshot easily, but it's around:

export_native_pdf_tiff - line 218
export_steps - lines 398/399
export_for_ocr - line 430
<main> - line 641

Thanks!

**Comment by cameron-stiller** [comment]
Release 1.4 will have this fix. Thank you for reporting it!

**Comment by thk007** [comment]
Legend, thanks!
